### ISSUE TITLE
RFC: Please review the initial version of CW-SDK

### ISSUE THREAD

**Issue by lukebarnard1** [morgen-so/morgen-cw-sdk#1]
Hey guys, can you please take a look at this repo and let me know whether you think it needs changes.

Remember, we're targeting early-adopters with this but there is still budget to polish things a bit and make it easier to use or better documented.

Also, if you could try it out yourselves that would be ideal (albeit without the `npm install` step for now, because it's currently not published).

@marcoancona @florianmorath @Pederzh

**Comment by marcoancona** [comment]
Here is some feedback @lukebarnard1 

Overall it looks great, simple, and effective. Great job 👍

My main concern is that this looks in between a CLI tool and an SDK, which could be confusing. In particular:
- Clear to me: I can `import` the SDK to write code that takes advantage of the `morgen` utils. 
- Confusing to me: The `run`, `upload`, and `trigger` seem more like CLI tools, so I would expect to do something like `morgen cw upload ./index.js` rather than triggering the upload programmatically in the same script where the workflow is defined 🤔 I am missing a use case?


Some more comments:
- It could be installed via `npm install git+https://github.com/morgen-so/morgen-cw-sdk`. We can either keep it this way while in beta (updating the doc) or publish it. However, I had to manually compile it. Maybe we can have a post-install script that calls `npm run build`? Or commit the dist folder.
- I would add to the docs that `typescript` should be available globally to be able to use `tsc`.
- I think "global.ts" should be listed in `files` in `tsconfig.json`. Better if all the .ts files are in a `/src` folder so we can configure Typescript to compile them all without involving other files.
- The `MORGEN_API_KEY` env should be set exactly as copied from the desktop app, but the documentation seems to suggest you need to prepend `ApiKey-`. It took a bit to understand why the authentication was not working.

Bonus

- Assuming to keep workflow definition and lifecycle management in the same file, allowing changing would be cool. This would need some rework of what the methods return and handling of a queue of promises. Nice to have but probably for a next version.

For example:

```ts

await cw.workflow(
 {
    name: "basic_example",
  },
  async function run(trigger) {
    log(trigger);
    console.log(trigger);
  }
)
.upload()
.trigger()
```

**Comment by lukebarnard1** [comment]
>Confusing to me: The run, upload, and trigger seem more like CLI tools, so I would expect to do something like morgen cw upload ./index.js rather than triggering the upload programmatically in the same script where the workflow is defined 🤔 I am missing a use case?

I did this based on your suggestion to do something similar to `airplane`. I looked at their docs, and this is essentially what they were doing.

And you're right – they are more like CLI tools, but the nice thing about doing it this way is that it:
- naturally + easily enables TypeScript (for utils etc. and in future the more advanced `morgen.events` API, for example)
- much easier to document (via TypeScript) and provide examples (examples can be a single file of config + implementation)
- means that we don't have to write any `bash` or CLI code, and we can stick to writing TypeScript (and if someone wants a bash script, they can still achieve that by wrapping it)
- we don't have to handle any building/compiling/bundling 🙏 

>It could be installed via npm install git+https://github.com/morgen-so/morgen-cw-sdk

Yep, let's keep it off of npm for now, sounds good. Meanwhile, I registered the `npm` user `morgenso` for future use.

>Maybe we can have a post-install script that calls npm run build

I actually don't know what's best practice here, but this sounds okay provided we make sure `tsc` is installed globally in a previous step.

>I think "global.ts" should be listed in files in tsconfig.json. 

This isn't necessary, tsc knows to include files that are imported to `index.ts`.

>Better if all the .ts files are in a /src

Fair 👍 

>but the documentation seems to suggest you need to prepend ApiKey-

I've been copying it from the db so... but if we give it to the user with that prefix then yep sure let's get rid.

> Bonus

Yep, but also it's useful to return other stuff from those methods. I don't love the current API but it seems pretty straight-forward to use and not too restrictive imo. But yeah let's consider nicer APIs next time

**Comment by marcoancona** [comment]
> I did this based on your suggestion to do something similar to airplane. I looked at their docs, and this is essentially what they were doing.

I can't see an example in their doc where the task is both defined and uploaded programmatically. They have a separate CLI tool for deploying, don't they? eg `airplane deploy` as [here](https://docs.airplane.dev/dev-lifecycle/deployments). But yes, CLI tools could come later.

> This isn't necessary, tsc knows to include files that are imported to index.ts.

I had to add it when I built (manually) the SDK because I was getting this: https://share.cleanshot.com/sTcMDTL1

**Comment by marcoancona** [comment]
One more:
- I suggest to check that this is a `custom-workflow` here: https://github.com/morgen-so/morgen-cw-sdk/blob/db1b680b58bac82c344d2882241b200d56280f95/index.ts#L83

**Comment by lukebarnard1** [comment]
>I can't see an example in their doc where the task is both defined and uploaded programmatically.

I think what's happened here is that I misinterpreted the `airplane` docs you [linked in my proposal](https://morgentechnologies.atlassian.net/wiki/spaces/M20/pages/1202651137?focusedCommentId=1204224001). I missed the fact that those functions are only uploaded when the user runs `airplane deploy`...

I think having a CLI to do the actual upload/deploy makes sense... but I think it's probably fine as it is for now. Using `ts-node` isn't that bad, it just feels a bit sketchy. 

We're a bit ahead of schedule, so maybe we could write a small CLI to do the upload/run/trigger tasks.

>I had to add it when I built (manually) the SDK because I was getting this:

Can you try again from scratch? I did and it seems fine now that `tsc` runs after installation.

@marcoancona
